apiVersion: v1
kind: Service
metadata:
  name: opsml-service
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: opsml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
      type: LoadBalancer
