apiVersion: v1
kind: Service
metadata:
  name: opsml
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: opsml
  ports:
    - name: apps
      protocol: TCP
      port: 80
      targetPort: 2000
  type: LoadBalancer